import { describe, it, expect, beforeAll, afterAll, afterEach, vi } from "vitest";
import { startTestDatabase, stopTestDatabase } from "../../tests/helpers/testDb.js";

let Payroll, createUserDirectly, registerPayrollCron, runMonthlyPayrollJob, resolvePreviousMonth;

// Dynamic imports, deferred until after startTestDatabase() has set every env
// var env.js requires at boot — payrollCron.js transitively imports
// payroll.service.js, which imports config/env.js directly (see
// backend/README.md's Testing section on why this pattern is needed).
beforeAll(async () => {
  await startTestDatabase();

  ({ default: Payroll } = await import("../modules/payroll/payroll.model.js"));
  ({ createUserDirectly } = await import("../../tests/helpers/authHelpers.js"));
  ({ registerPayrollCron, runMonthlyPayrollJob, resolvePreviousMonth } = await import(
    "./payrollCron.js"
  ));
});

afterEach(async () => {
  await Payroll.deleteMany({});
});

afterAll(async () => {
  await stopTestDatabase();
});

describe("resolvePreviousMonth", () => {
  it("returns the previous calendar month within the same year", () => {
    expect(resolvePreviousMonth(new Date(2026, 6, 1))).toEqual({ month: 6, year: 2026 }); // July -> June
  });

  it("wraps to December of the prior year when referenceDate is in January", () => {
    expect(resolvePreviousMonth(new Date(2027, 0, 1))).toEqual({ month: 12, year: 2026 });
  });
});

describe("registerPayrollCron", () => {
  it("schedules the monthly job at 00:05 on the 1st of every month", async () => {
    const cron = await import("node-cron");
    const scheduleSpy = vi.spyOn(cron.default, "schedule").mockImplementation(() => {});

    registerPayrollCron();

    expect(scheduleSpy).toHaveBeenCalledWith("5 0 1 * *", expect.any(Function));

    scheduleSpy.mockRestore();
  });
});

describe("runMonthlyPayrollJob", () => {
  it("bulk-runs Payroll for the previous month, identically to a manual bulk POST /payroll/run", async () => {
    const employee = await createUserDirectly({
      name: "Cron Employee",
      email: "cronemployee@test.local",
      password: "Password123",
      role: "employee",
    });
    employee.baseSalary = 24000;
    await employee.save();

    // referenceDate July 1 2026 -> previous month is June 2026 (month=6, year=2026).
    await runMonthlyPayrollJob(new Date(2026, 6, 1));

    const payroll = await Payroll.findOne({ employeeId: employee._id, month: 6, year: 2026 });

    expect(payroll).not.toBeNull();
    expect(payroll.daysInMonth).toBe(30);
    expect(payroll.grossAmount).toBe(0); // no Attendance/Leave records seeded for this employee
  });

  it("is idempotent — running it twice for the same reference date does not throw or duplicate the record", async () => {
    const employee = await createUserDirectly({
      name: "Cron Employee Two",
      email: "cronemployee2@test.local",
      password: "Password123",
      role: "employee",
    });
    employee.baseSalary = 24000;
    await employee.save();

    await runMonthlyPayrollJob(new Date(2026, 6, 1));
    await runMonthlyPayrollJob(new Date(2026, 6, 1));

    expect(await Payroll.countDocuments({ employeeId: employee._id, month: 6, year: 2026 })).toBe(1);
  });

  it("skips (does not error on) an active employee with no baseSalary set, same as a manual bulk run", async () => {
    const noSalaryEmployee = await createUserDirectly({
      name: "Cron Employee No Salary",
      email: "cronemployeenosalary@test.local",
      password: "Password123",
      role: "employee",
    });

    // Other employees created by earlier tests in this file (with baseSalary
    // already set) are still in the User collection and will also be
    // (re-)generated by this bulk run, since afterEach only clears Payroll —
    // this test only asserts the no-salary employee's own outcome.
    const result = await runMonthlyPayrollJob(new Date(2026, 6, 1));

    expect(result).not.toBeNull();
    const skippedIds = result.skipped.map((entry) => String(entry.employeeId));
    expect(skippedIds).toContain(String(noSalaryEmployee._id));
    expect(result.generated.map((record) => String(record.employeeId))).not.toContain(
      String(noSalaryEmployee._id)
    );
  });
});
